---
- name: "Setup.yml"
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:

  - name: Install epel repo (Rocky)
    dnf:
      name: "epel-release"
      state: latest
    when: ansible_os_family == "Rocky"

  - name: Upgrade all packages (Rocky)
    dnf:
      name: "*"
      state: latest
    when: ansible_os_family == "Rocky"

  - name: Install packages (Rocky)
    dnf:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bash-completion
      - curl
      - git
      - rsync
      - screen
      - tcpdump
      - vim
      - wget
    when: ansible_os_family == "Rocky"

  - name: Install dependencies for VirtualBox Guest Additions (Rocky)
    dnf:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - bzip2
      - dkms
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - perl
    when:
      - ansible_os_family == "Rocky"
      - ansible_virtualization_type == "virtualbox"


    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: httpd
        enabled: yes

    - name: Restart service httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

    #- name: Openscap report
    #  ansible.builtin.command: oscap  xccdf eval --report /var/www/html/server-scan.html  --profile xccdf_org.ssgproject.content_profile_cis_server_l1 /usr/share/xml/scap/ssg/content/ssg-rl8-ds.xml
        
